### PR TITLE
Add gradle build scripts

### PR DESCRIPTION
**Pull request by lavcraft**
Gradle build script is more simply and clean. I amm add build.gradle script and settings.gradle. It is work for me (Gradle 2.2.1)
If need, i can add gradle wrapper for standalone build (gradlew script)

### CODE REVIEW

**Comment by lavcraft** [comment]
travis ci : ./gradlew: Permission denied
Why ?

**Comment by dsyer** [comment]
I'd be happy to merge this if you can clean up the .gitignore (and leave the Maven build in place as well). Probably the permission is denied because the file is not executable? Also please fill out the contributor's agreement: https://support.springsource.com/spring_committer_signup

**Comment by lavcraft** [comment]
No, file is executable. I fix all and migrate to spring-cloud release version in next week. Thanks for support )

**Comment by lavcraft** [comment]
Fix permission denied. Clean .gitignore file (add only really needed patterns). Build complete, test passes ) https://travis-ci.org/lavcraft/eureka.svg?branch=gradle-support

**Comment by lavcraft** [comment]
Spring commiter sognup confirmation code 112220150314061440

**Comment by alok001** [comment]
Hello Guys 

I am new to spring boot and all was trying to configure eureka server. Below are details and error. Need help here

pom.xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.Vehicle</groupId>
	<artifactId>VehicleEureka-service</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>jar</packaging>

	<name>VehicleEureka-service</name>
	<description>Demo project for Spring Boot</description>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.5.9.RELEASE</version>
		<relativePath/> 
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
		<spring-cloud.version>Edgware.RELEASE</spring-cloud.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-eureka-server</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
</project>

application main class

@EnableEurekaServer
@SpringBootApplication
public class VehicleEurekaServiceApplication {

	public static void main(String[] args) {
		SpringApplication.run(VehicleEurekaServiceApplication.class, args);
	}
}
application.properties
server.port=8070

application.yml
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

Error:
Post-processing of merged bean definition failed; nested exception is java.lang.NoClassDefFoundError: org/apache/http/config/RegistryBuilder

**Pull request closed without merging**
